### ISSUE TITLE
bug: Passing a gitlab git url to the `--templates-url` option results in a `403` error

### ISSUE THREAD

**Issue by c12i** [holochain/scaffolding#197]
### How to reproduce

- Run `hc-scaffold web-app --templates-url https://gitlab.com/c12i/minimal-templates.git`
- Choose an app name
- The error below is printed out

```shell
Received response status: 403
Error: No templates found in the given git repository (a template is a folder located inside the ".templates" folder
```

Cause: this error stems from `degit` not being able to download the tarball from the repo due to signin to gitlab being required

**Comment by EskandarAtrakchi** [comment]
```  403 ```  means forbidden status when trying to access the GitLab repo 
This could be because of the authentication problem! let's try the following 

1. access token: GitLab often uses access tokens for authentication. Could you pass the access token in the URL or as an environment variable? 
```bash
hc-scaffold web-app --templates-url https://username:access-token@gitlab.com/c12i/minimal-templates.git
```
Or set it as an environment variable: 
```bash
export GITLAB_ACCESS_TOKEN=your-access-token
hc-scaffold web-app --templates-url https://gitlab.com/c12i/minimal-templates.git
```
just remember to replace ```  "username" ```  and ```  "access-token" ```  with your GitLab username and access token.
2. Check if the scaffold tool supports the GitLab API version used by the repository
3. check if you are on the correct ``` HTTPS ``` or ``` SSH ``` format 
4. maybe do some debugging?

**Comment by c12i** [comment]
@EskandarAtrakchi thanks for your recommendation, but unfortunately this does not work, since `degit` doesn't really communicate with the gitlab api but rather tries to download the repository tarball from a formerly public URL

**Comment by EskandarAtrakchi** [comment]
@c12i hmmm... consider running the command with additional debugging options to gather more information about the issue. This might help identify the root cause of the problem.
