### ISSUE TITLE
Custom template nix wrapper results in `Error: unmatching template`

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/scaffolding#247]
Using the [holochain-open-dev template](https://github.com/holochain-open-dev/template) with the recently merged https://github.com/holochain/scaffolding/pull/229 results in bad behavior between MacOs and linux users. This is because the template path gets written in the `package.json` like this: 

```json
  "hcScaffold": {
    "template": "/nix/store/c9lv5djdjlxxhk90g0idp4acapq2s0sv-hc-scaffold/template"
  }
```

And nix store paths are not consistent across platforms, so if I upload this repository and someone with another platform runs it, they are going to get an `Error: unmatching template`.

The custom template is internally setting the `--template` argument in every call to the scaffolding tool, and all that information is already embedded in the `hc-scaffold` binary that's available on the `nix develop` shell that the developers use. So in this case **I would actually like to disable that the template used to scaffold the project is written to the package.json**. Something like a `--disable-template-persistence` would suffice for me, but there is many different ways to implement something like this so I'm open to suggestions.

**Comment by c12i** [comment]
Thanks for spotting this issue. Here is how I think we can solve this without introducing a new flag

I think we can retain the storing the `template` in the `package.json`, but only if the template is one of `vue`, `lit`, `svelte`, or `vanilla`.

If the `template` is a local path to a local directory, we opt out of writing to the `package.json` and expect the user to have to provide the `--template` for each command

If the `template` is a path to the nix store, meaning that the user is using a custom template, we also opt out of writing to the `package.json`, since the custom template internally sets the `--template` argument.

what do you think @guillemcordoba?

**Comment by guillemcordoba** [comment]
Perfect! That works wonderfully for me. Thanks!

**Comment by guillemcordoba** [comment]
This is broken again with the latest `develop` branch.
