### ISSUE TITLE
Disable reformatting of unaffected files

### ISSUE THREAD

**Issue by matthme** [holochain/scaffolding#261]
It seems that the scaffolding tool re-formats files even if they have been unaffected by a scaffolding step. For example if I create two entry types, then I add my personal inline-comments in a file about entry type A and later scaffold a collection for entry type B, my personal inline-comments for entry type A get removed by the scaffolding tool.
Also if my IDE changed the formatting, files get re-formatted by the scaffolding tool in conflicting ways. In that way it is really cumbersome to distinguish which changes are merely formatting changes (or removal of my own inline comments) and where there are actual code changes.
This is especially inconvenient if one adds custom code logic in between scaffolding steps and wants to make sure nothing of one's own code logic has been affected by a scaffolding step.
It would be great to at least not have the scaffolding tool re-format files that are unaffected by a scaffolding step in regards of actual code logic.

**Comment by c12i** [comment]
I've observed that comments are being deleted, as I noted when opening issue #167. Initially, I assumed this was expected behaviour, as there were no responses clarifying if it was a problem. I'm willing to investigate this issue further.

Regarding the change in formatting observed in the Rust code generated by scaffolding, it appears to stem from the use of [prettyplease](https://lib.rs/crates/prettyplease) for programmatic reformatting. This behaviour differs from `rustfmt`, which unfortunately does not expose its API publicly, making programmatic calls challenging as discussed [here](https://users.rust-lang.org/t/how-to-format-a-tokenstream-with-rustfmt/84083/4). I will explore alternative methods for formatting.

Proper code formatting is important in Rust code gen, particularly because the initial code generated from existing code often loses its formatting when converting strings to token streams.

I will continue to investigate these issues and provide updates as I find more information.

**Comment by matthme** [comment]
It would already be a big improvement if it would only change formatting of files that are actually actively altered by the scaffolding tool if that's possible. Because at the moment the scaffolding tool changes the formatting even of files that in which it does not change any of the code logic and then it's cumbersome to figure out in which files scaffolding made actual changes vs. only formatting changes.

**Comment by c12i** [comment]
Yes, this quite a blow.

I figured out why this happens though, the comments are removed as a result of [this line here](https://github.com/holochain/scaffolding/blob/5227734ec6bdf7c6f2dfde1934cefc3df445b5cb/src/utils.rs#L175), which replaces doc comments `///` with regular comments `//`.

Since the code that get's programatically modified by scaffolding uses the `syn` and `quote` crates, which do not treat regular comments `//` as tokens, they end up getting lost. There doesn't seem to be a direct way to preserve comments from the research I have done.

On the other hand, doc comments `///` get preserved. If we remove the `.replace` call in the line of code I shared, we will preserve these comments, including the one you shared above. The only issue with leaving it like so would be that we could end up having doc comments in unnecessary places in rust code such as enum variants inside a `match` arm for example. While this will compile, it will produce a lot of warnings.
